profile=gpu-hq    # allow for higher quality playback
vo=gpu
gpu-api=opengl

osc=no            # disable on-screen controller
volume=75         # set volume to 75

sub-font="Roboto"
sub-font-size=40

screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=1
screenshot-directory="~/Pictures/Screenshots"
screenshot-template="mpv-%F-%wH%wM%wS%wT_%03n"
