# allow for higher quality playback
profile=gpu-hq
vo=gpu
gpu-api=opengl

# set volume to 75
volume=75

# disable on-screen controller
osc=no

sub-font="Roboto"
sub-font-size=40

# screenshots
screenshot-directory="~/Pictures/Screenshots"
screenshot-template="mpv_%F-%wH%wM%wS%wT_%03n"
screenshot-format=png
screenshot-high-bit-depth=yes
screenshot-png-compression=1
