# general settings
set-option -g default-terminal st-256color

set -g status-keys vi
set -g mode-keys vi

set -g base-index 1
set -g pane-base-index 1

set -g automatic-rename off
set -g renumber-windows on
set -g monitor-activity on
set -g visual-activity off

# colorscheme
set -g status-style fg=default,bg=default
set -g status-left '#[fg=colour15,bold]#I '
set -g status-right ' #[fg=colour14,bold]#S'

set -g window-status-current-format ' #W '
set -g window-status-current-style fg=colour12,bold

set -g window-status-format ' #W '
set -g window-status-style fg=colour7

set -g pane-active-border-style fg=colour12,bg=default
set -g pane-border-style fg=colour8,bg=default

# keybindings
unbind C-b
set -g prefix C-a

unbind '"'
bind | split-window -h

unbind %
bind - split-window -v

unbind h
bind h select-pane -L

unbind j
bind j select-pane -D

unbind k
bind k select-pane -U

unbind l
bind l select-pane -R
